### ISSUE TITLE
didc bind -t create named struct for inline tuple record params

### ISSUE THREAD

**Issue by lastmjs** [dfinity/candid#346] opened 2022-05-06 16:56 UTC
With `didc bind -t` the generated Rust code for inline records uses a custom named struct, so that the Rust function actually references a named struct instead of an anonymous struct in the param. It would be great if the same thing could be done for tuple structs. This is breaking my code because of some traits that would be hard to derive for a heterogeneous tuple struct. If tuple structs and regular structs were treated the same by `didc bind -t` then my code should automatically work.

**Comment by chenyan-dfinity** [comment] 2022-05-11 00:05
Duplicate of #255

**Closed by chenyan-dfinity** 2022-05-11 00:05 UTC
Labels: enhancement
