### ISSUE TITLE
didc -t rs should implement serialize for records and variants

### ISSUE THREAD

**Issue by lastmjs** [dfinity/candid#324] opened 2022-03-18 19:45 UTC
**Is your feature request related to a problem? Please describe.**

I am trying to use the generated Rust Candid types for use in Azle (TypeScript CDK), but I am running into this error when I try to have a record type as a parameter: `the trait Serialize is not implemented for `User`.

**Describe the solution you'd like**

For a simple Candid type like this:

```typescript
type User = record {
  id: text;
};
```

The Rust code currently looks like this:

```rust
use ic_cdk::export::candid::{self, CandidType, Deserialize};
use ic_cdk::api::call::CallResult;

#[derive(CandidType, Deserialize)]
struct User { id: String }
```

It would be nice if `Serialize` could also be in the derive macro:

```rust
use ic_cdk::export::candid::{self, CandidType, Deserialize, Serialize};
use ic_cdk::api::call::CallResult;

#[derive(CandidType, Deserialize, Serialize)]
struct User { id: String }
```

**Describe alternatives you've considered**

This could also be set as a feature in `Cargo.toml`.

**Additional context**

It would be nice to have the option of configuring things like this on the types output by `didc -t rust`. I am happy to do a PR, though I believe this fix is probably pretty simple.

**Comment by chenyan-dfinity** [comment] 2022-03-18 19:50
We plan to add a config struct to control the generated code, similar to the protobuf builder: https://docs.rs/prost-build/latest/prost_build/struct.Config.html#method.type_attribute

**Comment by lastmjs** [comment] 2022-03-18 19:51
Would this help when I am using `didc -t rs`? I will be using the command line or the Rust API.

**Comment by chenyan-dfinity** [comment] 2022-03-18 20:02
The CLI can take a config file as input, haven't thought about the format of the config file yet.

**Comment by lastmjs** [comment] 2022-03-31 14:17
Could we also add an option to choose if `nat` outputs `candid::Int` or `i128` and if `int` outputs `candid::Nat` or `u128`?

**Comment by chenyan-dfinity** [comment] 2022-03-31 16:31
Yep, all Candid types should be able to map to a user specified type.

**Comment by chenyan-dfinity** [comment] 2022-05-11 00:07
Duplicate of #255

**Closed by chenyan-dfinity** 2022-05-11 00:07 UTC
Labels: enhancement
