### ISSUE TITLE
Rust parsing Variants to Enums is not implemented

### ISSUE THREAD

**Issue by Arnor1711** [dfinity/candid#253] opened 2021-06-29 09:58 UTC
Using candid specifications with variants gives me a compiler error `help: message: not implemented`. I stumbled on this when I wanted to use variants from a Motoko Service in Rust.
I guess this comes from `declare_variant` function using the unimplemented function `usage_variant` in the rust `codegen` module.
Are there any plans on an implementation for that?

**Comment by chenyan-dfinity** [comment] 2021-06-30 18:00
The `codegen` module is out-dated. We are working on a new Rust binding, see https://github.com/dfinity/candid/issues/255.

Closing this as a duplicate of https://github.com/dfinity/candid/issues/255

**Closed by chenyan-dfinity** 2021-06-30 18:00 UTC
