### ISSUE TITLE
Newtype structs serialized with `Encode!` fail to deserialize with `Decode!`

### ISSUE THREAD

**Issue by alin-at-dfinity** [dfinity/candid#97] opened 2020-09-03 16:11 UTC
Minimal repro:
```rust
use candid::{CandidType, Decode, Deserialize, Encode};
fn main() {
    #[derive(CandidType, Deserialize)]
    struct Wrapper(Vec<usize>);
    let w = Wrapper(vec![1]);
    let b = candid::Encode!(&w).expect("failed to encode");
    candid::Decode!(&b[..], Wrapper).expect("failed to decode");
}
```
fails with:
```
thread 'X' panicked at 'failed to decode: 
Message: "Type mismatch. Type on the wire: Vec; Provided type: Nat64"
States:
Trailing type: [I(-8)]
Trailing value: [01, 01, 00, 00, 00, 00, 00, 00, 00]
Type table: [[I(-20), U(1), U(0), I(1)], [I(-19), I(-8)]]
Remaining value types: []
```

**Comment by chenyan-dfinity** [comment] 2020-09-03 17:40
Duplicate of https://github.com/dfinity/candid/issues/43

This was fixed in `0.5.3`, and I just confirmed the example above works on master.

**Closed by chenyan-dfinity** 2020-09-03 17:40 UTC
